[pytest]

addopts =
        -v
        -s
        --strict-markers

testpaths = selenium_tests

markers =
    smoke: Дымовые тесты для критического функционала
    regression: Полный набор регрессионных тестов
    slow: Медленные тесты (например, с доступом к сети)